consul-server:
  image: weyforth/rancher-consul-server:latest
  command: [-bootstrap-expect, 1]
  ports:
  - '8300:8300/tcp'
  - '8301:8301/tcp'
  - '8301:8301/udp'
  - '8302:8302/tcp'
  - '8302:8302/udp'
  - '8400:8400/tcp'
  - '8500:8500/tcp'
  - '8600:8600/tcp'
  - '8600:8600/udp'
  - '53:53/udp'
  labels:
    io.rancher.scheduler.affinity:host_label: consul.role=server

