consul-agent:
  image: weyforth/rancher-consul-agent:latest
  command: [-retry-join, 10.42.191.33]
  ports:
  - '8300:8300/tcp'
  - '8301:8301/tcp'
  - '8301:8301/udp'
  - '8302:8302/tcp'
  - '8302:8302/udp'
  - '8400:8400/tcp'
  - '8500:8500/tcp'
  - '8600:8600/tcp'
  - '8600:8600/udp'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label_ne: consul.role=server
